 # Syntax HighLight
  [[plugins]]
  repo = 'cespare/vim-toml'
  on_ft = 'toml'

  [[plugins]]
  repo = 'posva/vim-vue'
  on_ft = 'vue'

  [[plugins]]
  repo = 'elzr/vim-json'
  on_ft = 'json'

  [[plugins]]
  repo = 'tmux-plugins/vim-tmux'
  on_ft = 'tmux'

# React
  [[plugins]]
  repo = 'pangloss/vim-javascript'
  on_ft = ['javascript', 'javascript.jsx']

  [[plugins]]
  repo = 'maxmellon/vim-jsx-pretty'
  on_ft = ['javascript', 'javascript.jsx']

  [[plugins]]
  repo = 'alampros/vim-styled-jsx'
  on_ft = ['javascript', 'javascript.jsx']

  [[plugins]]
  repo = 'moll/vim-node'
  on_ft = ['javascript'] 

  [[plugins]]
  repo = 'glidenote/memolist.vim'
  hook_add = '''
    let g:memolist_path = "~/GoogleDrive/memo"
    nnoremap <Leader>mn :MemoNew<CR>
    nnoremap <Leader>ml :MemoList<CR>
    nnoremap <Leader>mg :MemoGrep<CR>
  '''

# Ruby関連
  [[plugins]]
  repo = 'tpope/vim-rails'
  on_ft = ['rb']
  [[plugins]]
  repo = 'ngmy/vim-rubocop'
  on_ft = ['rb']

