# ヘルプ日本語化
  [[plugins]]
  repo = 'vim-jp/vimdoc-ja'

# パッケージマネージャ
  [[plugins]]
  repo = 'Shougo/dein.vim'

# 非同期処理のため
  [[plugins]]
  repo = 'Shougo/vimproc.vim'
  build = 'make'

# 統合インターフェース関連
  [[plugins]]
  repo = 'Shougo/neomru.vim'
  on_path = '.*'
  
  [[plugins]]
  repo = 'Shougo/unite.vim'
  depends = 'neomru.vim'

#  [[plugins]]
#  repo = 'Shougo/denite.nvim'
#  hook_add = '''
#    source ~/.config/nvim/plugins/denite.vim 
#  '''
  
# ファイラー
  [[plugins]]
  repo = 'Shougo/vimfiler.vim'

# 選択したコードを実行できる
  [[plugins]]
  repo = 'thinca/vim-quickrun'

  [[plugins]]
  repo = 'editorconfig/editorconfig-vim'
  
  [[plugins]]
  repo = 'majutsushi/tagbar'
  
  [[plugins]]
  repo = 'bling/vim-airline'

# 補完機能
  [[plugins]]
  repo = 'Shougo/context_filetype.vim'

  [[plugins]]
  repo = 'roxma/nvim-yarp'

  [[plugins]]
  repo = 'roxma/vim-hug-neovim-rpc'

  [[plugins]]
  repo = 'Shougo/neosnippet-snippets'
  depends = ['neosnippet.vim']

# 非同期コードチェッカー
  [[plugins]]
  repo = 'w0rp/ale'
  hook_source = '''
  
  '''

# カッコ系
  [[plugins]]
  repo = 'tpope/vim-endwise'
  [[plugins]]
  repo = 'tpope/vim-surround'
  [[plugins]]
  repo = 'cohama/lexima.vim'

# テーブル系
  [[plugins]]
  repo = 'godlygeek/tabular'
  [[plugins]]
  repo = 'dhruvasagar/vim-table-mode'

# Syntax checker
  [[plugins]]
  repo = 'scrooloose/syntastic'

# Syntax HighLight
  [[plugins]]
  repo = 'cespare/vim-toml'
  on_ft = 'toml'

  [[plugins]]
  repo = 'posva/vim-vue'
  on_ft = 'vue'

  [[plugins]]
  repo = 'elzr/vim-json'
  on_ft = ['json']

  [[plugins]]
  repo = 'tmux-plugins/vim-tmux'
  on_ft = ['tmux']

# Markdown用
  [[plugins]]
  repo = 'tyru/open-browser.vim'
  hook_add = '''
    let g:netrw_nogx = 1
    augroup OpenBrowserSettings
      nmap gx <Plug>(openbrowser-smart-search)
      vmap gx <Plug>(openbrowser-smart-search)
    augroup END
  '''

  [[plugins]]
  repo = 'kannokanno/previm'
  on_cmd = 'PrevimOpen'
  depends = 'open-browser.vim'
  hook_add = '''
    let g:previm_open_cmd = 'open -a Google\ Chrome'
    augroup PrevimSettings
      autocmd!
      autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
      nnoremap <silent> <C-m> :PrevimOpen<CR>
    augroup END
  '''

  [[plugins]]
  repo = 'plasticboy/vim-markdown'
  hook_add = '''
    " 折りたたみOFF
    let g:vim_markdown_folding_disabled = 1
    " 以下2つは問題が出るためON
    " https://github.com/plasticboy/vim-markdown#do-not-automatically-insert-bulletpoints
    let g:vim_markdown_auto_insert_bullets = 0
    let g:vim_markdown_new_list_item_indent = 0
  '''

# 移動
  [[plugins]]
  repo = 'easymotion/vim-easymotion'

# IDEみたいにするために
  [[plugins]]
  repo = 'scrooloose/nerdtree'
  hook_add = '''
    let NERDTreeShowHidden=1
    nnoremap <silent><C-e> :NERDTreeToggle<CR>

    "引数なしでvimを開いたらNERDTreeを起動、
    "引数ありならNERDTreeは起動せず、引数で渡されたファイルを開く。
    autocmd vimenter * if !argc() | NERDTree | endif

    "他のバッファをすべて閉じた時にNERDTreeが開いていたらNERDTreeも一緒に閉じる。
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
  '''
  [[plugins]]
  repo = 'ryanoasis/vim-devicons'
  [[plugins]]
  repo = 'Xuyuanp/nerdtree-git-plugin'

  [[plugins]]
  repo ='junegunn/fzf'
  build = './install --all'
  merged =  0

  [[plugins]]
  repo ='junegunn/fzf.vim'
  depends = 'fzf'
  hook_add = '''
    nnoremap <silent> <Leader>f :Ag<CR>
    nnoremap <silent> <Leader>F :GFiles<CR>
    nnoremap <silent> <Leader>gf :GFiles?<CR>
    nnoremap <silent> <Leader>gd :Gdiff<CR>
    nnoremap <silent> <Leader>gc :Commits<CR>
    nnoremap <silent> <Leader>l :BLines<CR>
    nnoremap <silent> <Leader>h :History<CR>
    nnoremap <silent> <Leader>m :Mark<CR><Paste>
  '''

# Git操作
  [[plugins]]
  repo = 'tpope/vim-fugitive'

  [[plugins]]
  repo = 'haya14busa/vim-edgemotion'

  [[plugins]]
  repo = "tpope/vim-commentary"
